### ISSUE TITLE
fun4MeanShift meanshift G is gaussian

### ISSUE THREAD

**Issue by ahyunSeo** [aimerykong/Recurrent-Pixel-Embedding-for-Instance-Grouping#6]
Hello,

Thank you for your nice work.
I'm looking into your paper and code, but I have a minor issue. 
I'm focusing on the fun4meanshift module.
It seems like 

> exp(delta^2*x'*y -delta^2 )

is expressed as 
`outputs{1} = exp((inputs{1}-1)/(obj.delta^2));`
in this line,
https://github.com/aimerykong/Recurrent-Pixel-Embedding-for-Instance-Grouping/blob/master/libs/fun4MeanShift/meanshift_G_is_Gaussian.m#L16

Can you tell me how the delta^2 end up in the denominator?
I looked up at the paper, Appendix 2.1. equation (8) seems to have delta^2 in the numerator.
I checked the issue here,
https://github.com/aimerykong/Recurrent-Pixel-Embedding-for-Instance-Grouping/issues/4
but I still have no idea why.
Could you help me out?

Thanks,
Ahyun

**Comment by aimerykong** [comment]
Hi, Ahyun,

Thanks for your interest. This is a good catch. I should apologize for the
messy notation in the code, what I mean by delta in the code is **NOT** the
one in the paper --

In the code, I denote the bandwidth (GaussianBandwidth) by delta, which I
should have used another different variable name. The GaussianBandwidth is
closely related to the margin used for embedding learning, as described in
Section 4.1, where I used delta as well to derive some theory. So your
confusion comes from my messy notations, and the two delta's are actually
inverse to each other from the code and paper....

Thanks again for checking the closed issue. In that issue, I explain how
the Euclidean distance based kernel and von Mises Fisher kernel are
equivalent, except to a scalar factor. But it is true, both confusions are
because of that I didn't put things neatly in terms of notation.

Hope this helps.

Regards,
Shu

**Comment by ahyunSeo** [comment]
Hello,

Thank you for your fast and kind reply.
However, I'm still confused with the term bandwidth.
Are kernel bandwidth and GaussianBandwidth different?
In the section 4 and Appendix the kernel bandwidth delta is still in the numerator.

Or did you mean you set your delta in code as 
> delta_code = 1/delta_paper = (1-alpha_paper) / 3

like following?
<img width="99" alt="screen shot 2018-12-03 at 11 00 30 am" src="https://user-images.githubusercontent.com/22852018/49348776-c6a0b080-f6ea-11e8-9951-47809698b578.png">

Thanks,
Ahyun

**Comment by aimerykong** [comment]
Hi, Ahyun,

Yes. What you wrote is exactly what I mean in the code and paper. The
kernel bandwidth (1/delta_paper) and GaussianBandwidth (delta_paper) are
the same. In literature, people call delta_code = 1/delta_paper the
bandwidth. Let me know other questions. Thanks!

Regards,
Shu
